service: webCompany-serverless

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tableName: ${self:custom.stage}-company

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: dev

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    tableName: ${self:custom.tableName}

  # permissions for all of your functions can be set here
  iamRoleStatements:
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [CompanyTable, Arn]

  functions:
    app:
      handler: user-settings.index
      events:
        - http: ANY /
        - http: "ANY {proxy+}"
    createCompany:
      handler: company.handler
      events:
        - http:
            path: /company
            method: POST
            cors: true
    getCompany:
      handler: company.handler
      events:
        - http:
            path: /company/{proxy+}
            method: GET
            cors: true
    putCompany:
      handler: company.handler
      events:
        - http:
            path: /company/{proxy+}
            method: PUT
            cors: true
    deleteCompany:
      handler: company.handler
      events:
        - http:
            path: /company/{proxy+}
            method: DELETE
            cors: true

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
  # S3
  - ${file(resources/s3-bucket.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
