service: webCustomer-serverless

provider:
  name: aws
  runtime: nodejs10.x
  region: us-west-2
  stage: dev

  functions:
  getCustomers:
    handler: handler.getCustomers
    events:
      - http: GET
